
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login?serverTimezone=Asia/Seoul
    username:
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update    # ??? ????? ??? ? ?? create? ???? ?? ?????? ???? create??? ??? ????? update? ??????.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity(?????)?? ??? ??? db? ??? ????.
      use-new-id-generator-mappings: false    # jpa? db ?? ??? ???? ???.(false)
    show-sql: true        # ???? ??? ???(true)
    properties:
      hibernate.format_sql: true  # ???? ??? ???? ??? ???? ???

#    jackson:
#      serialization:
#        fail-on-empty-beans: false
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            client-id: 
            client-secret: 
            scope:
              - email
              - profile

          naver:
            client-id: 
            client-secret: 
            scope:
              - name
              - email
#              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
